07_django/INSTA/accounts/urls.py
from django.urls import path
from . import views

app_name = "accounts"

urlpatterns = [
    path('signup/', views.signup, name="signup"),
    path('login/', views.login, name="login"),
    path('logout/', views.logout, name="logout"),
    path('users/<str:username>/', views.user_detail, name="user_detail"),
    path('follow/<str:username>/', views.toggle_follow, name="toggle_follow"),

]

07_django/INSTA/insta/urls.py
from django.contrib import admin
from django.urls import path, include

#Media 업로드를 위해서
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('insta/', include('posts.urls')),
    path('accounts/', include('accounts.urls'))
]
#개발서버에서 자동적으로 이미지등록이 안되어서 써줘야 하는 코드.
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
#if env dev => [...]
#if env prod => None (스태틱 함수 리턴값이)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

07_django/INSTA/posts/urls.py
from . import views
from django.urls import path

app_name = 'posts'
urlpatterns = [
    path('', views.post_list, name="post_list"),
    path('create/', views.create_post, name="create_post"),
    path('<int:post_id>/update/', views.update_post, name="update_post"),
    path('<int:post_id>/delete/', views.delete_post, name="delete_post"),
    path('<int:post_id>/comment', views.create_comment, name="create_comment"),
    path('<int:post_id>/comment/<int:comment_id>/', views.delete_comment, name="delete_comment"),
    path('<int:post_id>/like/', views.toggle_like, name='toggle_like'),
    path('<str:tag>/posts/', views.tag_posts, name='tag_posts')
]

07_django/INSTA/posts/models.py
from django.db import models
from imagekit.models import ProcessedImageField
from imagekit.processors import ResizeToFill
from django_extensions.db.models import TimeStampedModel
import os
from django.conf import settings
from django.contrib.auth.models import User

ENV = os.environ.get('ENVIRONMENT', 'development')
if ENV == 'development':
    from IPython import embed
    from faker import Faker
faker = Faker()
# Create your models here.


class HashTag(TimeStampedModel):
    content = models.CharField(max_length=20, unique=True)

    def __str__(self):
        return self.content

    class Meta:
        ordering = ['content']


class Post(TimeStampedModel):
    content = models.CharField(max_length=140)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.PROTECT)
    like_users = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='like_posts')
    tags = models.ManyToManyField(HashTag, blank=True, related_name='posts')
    #배포시엔 삭제
    @classmethod
    def dummy(cls, n=10):
        for i in range(n):
            Post.objects.create(content=faker.text(120))

    class Meta:
        ordering = ['-created']


class Image(TimeStampedModel):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    file = ProcessedImageField(
        blank=True,
        upload_to='posts/images',
        processors=[ResizeToFill(600,600)],
        format='JPEG',
        options={'quality': 90}
    )

class Comment(TimeStampedModel):
    content = models.CharField(max_length=100)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

07_django/INSTA/posts/forms.py
from django import forms
from .models import Post, Image, Comment

class CommentModelForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['content']

class PostModelForm(forms.ModelForm):
    # content = forms.EmailField(label='Your Email')
    class Meta:
        model = Post
        fields = ['content']
        #fields = ['content', ....]

class ImageModelForm(forms.ModelForm):
    class Meta:
        model = Image
        fields = ['file', ]
        widgets = {
            'file': forms.FileInput(attrs={'multiple': True})
        }

07_django/INSTA/posts/views.py
from django.shortcuts import render, redirect, get_object_or_404, HttpResponseRedirect
from django.http import JsonResponse, HttpResponseBadRequest
from django.views.decorators.http import require_GET, require_POST, require_http_methods
from .models import *
from .forms import PostModelForm, ImageModelForm, CommentModelForm
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from IPython import embed
# Create your views here.


@require_GET
def post_list(request):
    posts = Post.objects.all()
    form = CommentModelForm()
    return render(request, 'posts/list.html', {'posts': posts, 'form': form})


@login_required
@require_http_methods(['GET', 'POST'])
def create_post(request):
    if request.method == 'POST':
        post_form = PostModelForm(data=request.POST)
        if post_form.is_valid():
            post = post_form.save(commit=False)
            post.user = request.user
            post.save()

            #create HashTag #hi #ssafy #20층
            content = post_form.cleaned_data.get('content')
            words = content.split()
            for word in words:
                if word[0] == '#':
                    word = word[1:]
                    tag = HashTag.objects.get_or_create(content=word)  #(HashTagObj, True)    (HashTagObj, False) 없어서만들었음
                    post.tags.add(tag[0])
                    if tag[1]:
                        messages.add_message(request, messages.SUCCESS, f'#{tag[0].content}를 처음으로 추가하셨어요!')

            for image in request.FILES.getlist('file'):
                request.FILES['file'] = image
                image_form = ImageModelForm(files=request.FILES)
                if image_form.is_valid():
                    image = image_form.save(commit=False)
                    image.post = post
                    image.save()
            return redirect('posts:post_list')
    else:
        post_form = PostModelForm()
    image_form = ImageModelForm()
    return render(request, 'posts/form.html', {
        'post_form': post_form,
        'image_form': image_form,
    })


@login_required
@require_http_methods(['GET', 'POST'])
def update_post(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    if post.user == request.user: #지금 수정하려는 post 작성자가 요청보낸 사람이냐?
        if request.method == 'POST':
            post_form = PostModelForm(request.POST, instance=post)
            if post_form.is_valid():
                post = post_form.save(commit=False)
                post.user = request.user
                post.save()
                #update HashTag
                post.tags.clear()
                content = post_form.cleaned_data.get('content')
                words = content.split()
                for word in words:
                    if word[0] == '#':
                        word = word[1:]
                        tag = HashTag.objects.get_or_create(
                            content=word)  # (HashTagObj, True)    (HashTagObj, False) 없어서만들었음
                        post.tags.add(tag[0])
                        if tag[1]:
                            messages.add_message(request, messages.SUCCESS, f'#{tag[0].content}를 처음으로 추가하셨어요!')
                return redirect('posts:post_list')
        else:
            post_form = PostModelForm(instance=post)
        return render(request, 'posts/form.html', {
            'post_form': post_form,
        })
    else:
        return redirect('posts:post_list')


@login_required
@require_POST
def delete_post(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    post.delete()
    return redirect('posts:post_list')

@login_required
@require_POST
def create_comment(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    if request.method == 'POST':
        form = CommentModelForm(data=request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.post = post
            comment.user = request.user
            comment.save()
            return HttpResponseRedirect(request.META.get('HTTP_REFERER'))
    else:
        form = CommentModelForm()
    return render(request, 'posts/form.html', {'post_form': form})


@require_POST
def delete_comment(request, post_id, comment_id):
    post = get_object_or_404(Post, id=post_id)
    comment = get_object_or_404(Comment, id=comment_id)
    comment.delete()
    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))


@require_POST
@login_required
def toggle_like(request, post_id):
    if request.is_ajax():
        user = request.user
        post = get_object_or_404(Post, id=post_id)
        is_active = True
        if user in post.like_users.all():
            post.like_users.remove(user)
            is_active = False
        else:
            post.like_users.add(user)
        return JsonResponse({'likeCount': post.like_users.count(), 'is_active':is_active})
    else:
        return HttpResponseBadRequest()


def tag_posts(request, tag):
    tag = get_object_or_404(HashTag, content=tag)
    posts = tag.posts.all()
    form = CommentModelForm()
    return render(request, 'posts/list.html', {'posts': posts, 'form':form})

07_django/INSTA/posts/templates/posts/_detail.html
{% load bootstrap4 %}

<!-- Modal -->
<div class="modal fade" id="modal{{ post.id }}" tabindex="-1" role="dialog" aria-labelledby="exampleModalLongTitle" aria-hidden="true">
  <div class="modal-dialog modal-xl modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLongTitle">Comments</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
      <div class="row">
        <div class="col-6">
            <article class="card">
                {% if post.image_set.all %}
                    <div id="post{{post.id}}" class="carousel slide carousel-fade" data-ride="carousel">
                        <div class="carousel-inner">
                            {% for image in post.image_set.all %}
                                <div class="carousel-item {% if forloop.counter == 1 %} active {% endif %}">
                                    <img src="{{ image.file.url }}" class="d-block w-100" alt="{{ image.file }}">
                                </div>
                            {% endfor %}
                        </div>
                        {% if post.image_set.count > 1 %}
                        <a class="carousel-control-prev" href="#post{{post.id}}" role="button" data-slide="prev">
                            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                            <span class="sr-only">Previous</span>
                        </a>
                        <a class="carousel-control-next" href="#post{{post.id}}" role="button" data-slide="next">
                            <span class="carousel-control-next-icon" aria-hidden="true"></span>
                            <span class="sr-only">Next</span>
                        </a>
                        {% endif %}
                    </div>

                {% else %}
                    <img src="http://lorempixel.com/600/600" alt="lorempixel" class="card-img-top" />
                {% endif %}
                <div class="card-body pb-1">
                    <div class="d-flex justify-content-between">
                        <h5 class="card-title">{{ post.user.username }}</h5>
                        {% if user.is_authenticated %}
                            <div>
                                {% if user in post.like_users.all %}
                                    <i class="like-button fas fa-heart fa-2x activate like-button-{{ post.id }}" data-id="{{ post.id }}"></i>
                                {% else %}
                                    <i class="like-button far fa-heart fa-2x like-button-{{ post.id }}" data-id="{{ post.id }}"></i>
                                {% endif %}
                                <span class="like-count-{{ post.id }}">{{ post.like_users.count }} likes</span>
                            </div>
                        {% else %}
                            <div class="float-right">
                                <a href="{% url 'accounts:signup' %}"><i class="like-button far fa-heart fa-2x text-muted" data-id="{{ post.id }}"></i></a>
                                <span id="like-count-{{ post.id }}">{{ post.like_users.count }} likes</span>
                            </div>
                        {% endif %}
                    </div>
                    <hr class="mt-0 mb-3">
                    <p class="card-text">{{ post.content }}</p>
                    <div class="mb-3">
                    {% for tag in post.tags.all %}
                        <a href="{% url 'posts:tag_posts' tag.content %}"><span>#{{ tag.content }} </span></a>
                        {% empty %}
                        <span class="text-white">태그없음</span>
                    {% endfor %}
                    </div>

                        <div class="row">
                            <p class="text-muted col-8 lh">{{ post.created }}</p>
                            {% if post.user == user %}
                            <a href="{% url 'posts:update_post' post.id %}" class="col-2 pl-5 pr-0 text-muted"><button class="btn btn-success">edit</button></a>
                            <form action="{% url 'posts:delete_post' post.id %}" method="post" class="col-2">
                            {% csrf_token %}
                                <input type="submit" value="delete" class="btn btn-danger">
                            </form>
                            {% else %}
                                <div></div>
                            {% endif %}
                        </div>

                </div>
            </article>
        </div>
      <div class="col-6">
          <form action="{% url 'posts:create_comment' post.id %}" method="post">
          {% csrf_token %}
              {% bootstrap_form form %}
              {% buttons %}
                  <input type="submit" value="submit" class="btn btn-primary float-right mr-4 mb-4">
              {% endbuttons %}
          </form>
        {% if post.comment_set.all %}
          <table class="table table-hover text-center">
          <tr><td>username</td><td>comment</td></tr>
            {% for comment in post.comment_set.all %}
                <tr>
                    <td><strong>{{ comment.user.username }}</strong></td>
                    <td>{{ comment.content }}
                        {% if comment.user == user %}
                        <form action="{% url 'posts:delete_comment' post.id comment.id %}" method="post" class="float-right">
                            {% csrf_token %}
                            <input type="submit" value="delete" class="btn btn-warning btn-sm">
                        </form>
                        {% endif %}
                    </td>
                </tr>
            {% endfor %}
          </table>
        {% else %}
            댓글을 달아주세요!
        {% endif %}
      </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
  </div>
</div>

07_django/INSTA/posts/templates/posts/_post.html
{% load bootstrap4 %}

{% include 'posts/_detail.html' %}
<article class="card mb-5">
<a class= "text-reset" data-toggle="modal" data-target="#modal{{ post.id }}">
    {% if post.image_set.all %}
        <div id="carousel{{post.id}}" class="carousel slide carousel-fade" data-ride="carousel">
            <div class="carousel-inner">
                {% for image in post.image_set.all %}
                    <div class="carousel-item {% if forloop.counter == 1 %} active {% endif %}">
                        <img src="{{ image.file.url }}" class="d-block w-100" alt="{{ image.file }}">
                    </div>
                {% endfor %}
            </div>
        {% if post.image_set.count > 1 %}
            <a class="carousel-control-prev" href="#carousel{{post.id}}" role="button" data-slide="prev">
                <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                <span class="sr-only">Previous</span>
            </a>
            <a class="carousel-control-next" href="#carousel{{post.id}}" role="button" data-slide="next">
                <span class="carousel-control-next-icon" aria-hidden="true"></span>
                <span class="sr-only">Next</span>
            </a>
        {% endif %}
        </div>
    {% else %}
        <img src="http://lorempixel.com/600/600" alt="lorempixel" class="card-img-top" />
    {% endif %}
</a>
    <div class="card-body">
        <div class="d-flex justify-content-between">
            <div>
                <h5 class="card-title d-inline"><a href="{% url 'accounts:user_detail' post.user.username %}" class="text-reset">{{ post.user.username }} </a></h5>
            </div>
            {% if user.is_authenticated %}
                <div>
                    {% if user in post.like_users.all %}
                        <i class="like-button fas fa-heart fa-2x activate like-button-{{ post.id }}" data-id="{{ post.id }}"></i>
                    {% else %}
                        <i class="like-button far fa-heart fa-2x like-button-{{ post.id }}" data-id="{{ post.id }}"></i>
                    {% endif %}
                    <span class="like-count-{{ post.id }}">{{ post.like_users.count }} likes</span>
                </div>
            {% else %}
                <div class="float-right">
                    <a href="{% url 'accounts:signup' %}"><i class="like-button far fa-heart fa-2x text-muted" data-id="{{ post.id }}"></i></a>
                    <span id="like-count-{{ post.id }}">{{ post.like_users.count }} likes</span>
                </div>
            {% endif %}

        </div>
        <hr class="mt-2 mb-3">
        <p class="card-text text-truncate">{{ post.content }}</p>
        <div class="text-truncate mb-1">
            {% for tag in post.tags.all %}
                <a href="{% url 'posts:tag_posts' tag.content %}"><span>#{{ tag.content }} </span></a>
                {% empty %}
                <span class="text-white">태그없음</span>
            {% endfor %}
        </div>
        <div class="row">
            <p class="text-muted col-7 lh m-0">{{ post.created }}</p>
            {% if post.user == user %}
                <a href="{% url 'posts:update_post' post.id %}" class="col-2 text-muted"><button class="text-truncate btn btn-success">edit</button></a>
                <form action="{% url 'posts:delete_post' post.id %}" method="post" class="col-3">
                {% csrf_token %}
                    <input type="submit" value="delete" class="btn btn-danger text-truncate">
                </form>
            {% else %}
                <div class="col-5"></div>
            {% endif %}
        </div>

    </div>
</article>

07_django/INSTA/posts/templates/posts/form.html
{% extends 'base.html' %}
{% load bootstrap4 %}


{% block body %}
    <h1 class="mt-5">Create and Update</h1>
    <hr class="my-5">
    <form action="#" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {% bootstrap_form post_form %}
    {% if image_form %}
    {% bootstrap_form image_form show_label=False %}
    {% endif %}
    {% buttons %}
        <button type="submit" class="btn btn-primary">Submit</button>
    {% endbuttons %}
    </form>

{% endblock %}

07_django/INSTA/posts/templates/posts/list.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% block body %}
    <h1 class="mt-5">Posts</h1>
    <hr class="my-5">
    <section class="card-columns">
        {% for post in posts %}
            {% include 'posts/_post.html' %}
        {% endfor %}
    </section>
{% endblock %}