07_django/base_prj/base_prj/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('sns/', include('sns.urls')),
    path('movie/', include('movie.urls')),
    path('accounts/', include('accounts.urls'))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

07_django/base_prj/sns/urls.py
from django.urls import path
from . import views
app_name = "sns"

urlpatterns = [
    path('', views.posting_list, name="posting_list"),
    path('<int:posting_id>/', views.posting_detail, name="posting_detail"),
    path('new/', views.create_posting, name="create_posting"),
    path('<int:posting_id>/edit/', views.edit_posting, name="edit_posting"),
    path('<int:posting_id>/delete/', views.delete_posting, name="delete_posting"),
    path('<int:posting_id>/comments/create/', views.create_comment, name="create_comment"),
    path('<int:posting_id>/delete/<int:comment_id>/', views.delete_comment, name="delete_comment"),
]

07_django/base_prj/sns/models.py
from django.db import models
from datetime import datetime
# Create your models here.


class Posting (models.Model):
    content = models.CharField(max_length=500)
    icon = models.CharField(max_length=20, default="fas fa-question")
    image = models.ImageField(blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f'{self.id}: {self.content[:10]}'


class Comment(models.Model):
    posting = models.ForeignKey(Posting, on_delete=models.CASCADE)
    content = models.CharField(max_length=200)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f'{self.id}: {self.content[:10]}'

07_django/base_prj/sns/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Posting, Comment
from django.contrib.auth.decorators import login_required
# Create your views here.


def posting_list(request):
    postings = Posting.objects.all()

    return render(request, 'sns/list.html', {'postings': postings})


def posting_detail(request, posting_id):
    posting = get_object_or_404(Posting, id=posting_id)
    comments = posting.comment_set.all()

    return render(request, 'sns/detail.html', {'posting': posting, 'comments':comments})

@login_required(login_url='/accounts/signin/')
def create_posting(request):
    if request.method == "POST":
        posting = Posting()
        posting.content = request.POST.get('content')
        posting.icon = request.POST.get('icon')
        posting.image = request.FILES.get('image')
        posting.save()

        return redirect('sns:posting_detail', posting.id)
    else:

        return redirect('sns:posting_list')


def edit_posting(request, posting_id):
    posting = Posting.objects.get(id=posting_id)
    if request.method == 'GET':
        icons = {'fas fa-question': '?', 'far fa-smile':':)', 'far fa-angry':':(', 'far fa-smile-wink': ';)', 'far fa-grin-hearts':'♡', }
        return render(request, 'sns/edit.html', {'posting': posting, 'icons': icons })
    else:
        posting.content = request.POST.get('content')
        posting.icon = request.POST.get('icon')
        if request.FILES.get('image'):
            posting.image = request.POST.get('image')
        posting.save()
        return redirect('sns:posting_detail', posting_id)


def delete_posting(request, posting_id):
    if request.method=='POST':
        posting = Posting.objects.get(id=posting_id)
        posting.delete()
        return redirect('sns:posting_list')
    else:
        return redirect('sns:posting_detail', posting_id)


def create_comment(request, posting_id):
    posting = get_object_or_404(Posting, id=posting_id)
    if request.method=='POST':
        comment = Comment()
        comment.content = request.POST.get('comment')
        comment.posting = posting
        comment.save()
    return redirect('sns:posting_detail', posting_id)


def delete_comment(request, posting_id, comment_id):
    if request.method == 'POST':
        comment = Comment.objects.get(id=comment_id)
        comment.delete()
    return redirect('sns:posting_detail', posting_id)

07_django/base_prj/sns/templates/sns/_header.html
<header class="mt-3">
    <form action="{% url 'sns:create_posting' %}" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="form-row align-items-center">
            <!-- icon select tag -->
            <div class="col-auto my-1">
                <label for="icon" class="sr-only">icon</label>
                <select name="icon" id="icon" class="custom-select mr-sm-2">
                    <option value="fas fa-question">?</option>
                    <option value="far fa-smile">:)</option>
                    <option value="far fa-angry">:(</option>
                    <option value="far fa-smile-wink">;)</option>
                    <option value="far fa-grin-hearts">♡</option>
                </select>
            </div>
            <!-- content input tag -->
            <div class="col-sm-6 my-1">
                <label for="content" class="sr-only">content</label>
                <input type="text" name="content" id="content" class="form-control" placeholder="Feels like.."/>
            </div>
            <!-- image file input tag -->
            <div class="col-sm-4 my-1 input-group">
                <div class="input-group-prepend">
                    <span class="input-group-text">Upload</span>
                </div>
                <div class="custom-file">
                    <input id="image" class="custom-file-input" name="image" type="file" accept="image/*">
                    <label for="image" class="custom-file-label">Choose image</label>
                </div>
            </div>
            <!-- submit button tag -->
            <div class="col-auto my-1">
                <button type="submit" class="btn btn-dark">Submit</button>
            </div>

        </div>
    </form>
</header>

07_django/base_prj/sns/templates/sns/_nav.html
<ul class="nav nav-tabs">
    <li class="nav-item">
        <a href="{% url 'sns:posting_list' %}" class="nav-link {% block list %}{% endblock %}">
            SNS
        </a>
    </li>
    <li class="nav-item">
        <a class="nav-link {% block detail %}{% endblock %}" aria-disabled="true">
            Detail
        </a>
    </li>
</ul>

07_django/base_prj/sns/templates/sns/base.html
<!doctype html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css"
          integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.1/css/all.css" integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">
    <title>My SNS</title>
</head>
<body>
    {%  include 'sns/_nav.html' %}

    <div class="container">
        {% block body %}
        {% endblock %}
    </div>

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
            integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
            crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js"
            integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut"
            crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js"
            integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k"
            crossorigin="anonymous"></script>
</body>
</html>

07_django/base_prj/sns/templates/sns/detail.html
{% extends 'sns/base.html' %}

{% block detail %}active{% endblock %}

{% block body %}
    <div class="row mt-3">
        <div class="col-12 col-md-6">
            <div class="card">
                {% if posting.image %}
                    <img src="{{ posting.image.url }}" alt="{{ posting.image }}" class="card-img-top">
                {% else %}
                   <img src="http://lorempixel.com/400/200/" alt="lorempixel" class="card-img-top">
                {%  endif %}
                <div class="card-body">
                    <i class="{{ posting.icon }} fa-3x"></i>
                    <hr>
                    <p class="card-text">{{ posting.content }}</p>
                </div>
            </div>

            <div class="card mt-2">
                <div class="card-body">
                    <form action="{% url 'sns:create_comment' posting.id %}" method="POST">
                        {% csrf_token %}
                        <label for="comment">Leave comment</label>
                        <input type="text" name="comment" id="comment" class="form-control" autofocus>
                    </form>
                </div>
            </div>
            <div class="btn-group mt-4 d-flex justify-content-end" role="group">
                <form method="POST" action="{% url 'sns:delete_posting' posting.id %}">
                    {% csrf_token %}
                    <input class="btn btn-danger" type="submit" value="Delete">
                </form>
                <a href="{% url 'sns:edit_posting' posting.id %}"><button class="btn btn-info ml-2">Edit</button></a>
            </div>
        </div>

        <div class="col-12 col-md-6">
            <div class="card">
                <ul class="list-group list-group-flush">
                    {% if comments %}
                        {% for comment in comments %}
                            <li class="list-group-item mb-1">
                            <div class="row justify-content-between">
                                <span class="align-middle">{{ comment.content }}</span>
                                <form action="{% url 'sns:delete_comment' posting.id comment.id %}" method="POST">
                                    {% csrf_token %}
                                    <input type="submit" class="btn p-0 btn-secondary btn-sm" value="delete">
                                </form>
                            </div>
                            </li>
                        {% endfor %}
                    {% else %}
                        <li class="list-group-item mb-1">No comments yet..</li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </div>



{% endblock %}

07_django/base_prj/sns/templates/sns/edit.html
{% extends 'sns/base.html' %}

{% block body %}
<header class="mt-3">
    <form action="{% url 'sns:edit_posting' posting.id %}" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="form-row align-items-center">
            <!-- icon select tag -->
            <div class="col-auto my-1">
                <label for="icon" class="sr-only">icon</label>
                <select name="icon" id="icon" class="custom-select mr-sm-2">
                    {% for icon,var in icons.items %}
                    <option value="{{ icon }}" {% if posting.icon == icon %} selected {% endif %}>{{ var }}</option>
                    {% endfor %}
                </select>
            </div>
            <!-- content input tag -->
            <div class="col-sm-6 my-1">
                <label for="content" class="sr-only">content</label>
                <input type="text" name="content" id="content" class="form-control" value="{{ posting.content}}" placeholder="Feels like.."/>
            </div>
            <!-- image file input tag -->
            <div class="col-sm-4 my-1 input-group">
                <div class="input-group-prepend">
                    <span class="input-group-text">Upload</span>
                </div>
                <div class="custom-file">
                    {% if posting.image %}
                        <input id="image" class="custom-file-input" name="image" type="file" accept="image/*" >
                        <label for="image" class="custom-file-label">Choose image</label>
                    {% else %}
                        <input id="image" class="custom-file-input" name="image" type="file" accept="image/*">
                        <label for="image" class="custom-file-label">Choose image</label>
                    {% endif %}
                </div>
            </div>
            <!-- submit button tag -->
            <div class="col-auto my-1">
                <button type="submit" class="btn btn-dark">Submit</button>
            </div>

        </div>
    </form>
</header>
    <div>
    <p class="m-auto">current image</p>
    </div>
    <div>
    <img class="m-auto" src="{{ posting.image.url }}" alt="{{ posting.image }}" width="150">
    </div>


{% endblock %}

07_django/base_prj/sns/templates/sns/list.html
{% extends 'sns/base.html' %}

{% block list %}active{% endblock %}

{% block body %}
    {% include 'sns/_header.html' %}
    <hr>
    {% if postings %}
        <section class="card-columns">
            {% for posting in postings %}
                    <article class="card mb-2">
                        <a href="{% url 'sns:posting_detail' posting.id %}">
                            {% if posting.image %}
                                <img src="{{ posting.image.url }}" alt="{{ posting.image }}" class="card-img-top image-fluid">
                            {% else %}
                                <img src="http://lorempixel.com/g/150/75" alt="random_img_{{ forloop.counter }}" class="card-img-top image-fluid">
                            {% endif %}
                        </a>
                        <div class="card-body">
                            <i class="{{ posting.icon }} fa-2x"></i>
                            <span class="float-right">댓글: {{ posting.comment_set.count }}</span>
                        <div class="list-inline">
                            <p class="text-right text-muted m-0"><small>작성일: {{ posting.created_at }}</small></p>
                            {% if posting.updated_at != posting.created_at %}
                                <p class="text-right text-muted m-0"><small>수정일: {{ posting.updated_at }}</small></p>
                            {% endif %}
                        </div>
                        </div>
                    </article>
            {% endfor %}
        </section>

    {% endif %}

{% endblock %}