07_django/review/board/urls.py
from django.urls import path
from . import views



app_name = 'board'

urlpatterns = [
    path('', views.index, name='index'),  # Domain/
    path('greeting/<str:name>/<str:role>/', views.greeting, name='greeting'),

    # Create
    # /articles/new => html (새로 작성하는 화면)
    path('articles/new/', views.article_new, name='article_new'),
    # /articles/create => DB new record
    path('articles/create/', views.article_create, name='article_create'),

    # Read
    # /articles => html (all articles)
    path('articles/list/', views.article_list, name='article_list'),
    # /articles/1 => html (article with id 1)
    path('articles/<int:id>/', views.article_detail, name='article_detail'),

    # Update
    # /articles/1/edit => html (article id=1 수정하는 화면)
    path('articles/<int:id>/edit/', views.article_edit, name='article_edit'),
    # /articles/1/update => DB update article id=1
    path('articles/<int:id>/update/', views.article_update, name='article_update'),

    # Delete
    # /articles/1/delete => DB delete article id=1
    path('articles/<int:id>/delete/', views.article_delete, name='article_delete'),

]

07_django/review/board_ad/urls.py
from django.urls import path
from . import views



app_name = 'board_ad'

urlpatterns = [
    # Read
    path('', views.posting_list, name='posting_list'),
    path('<int:posting_id>/', views.posting_detail, name='posting_detail'),
    # Create
    path('new/', views.posting_create, name='posting_create'),
    # Update
    path('<int:posting_id>/edit/', views.posting_update, name='posting_update'),
    # Delete
    path('<int:posting_id>/delete/', views.posting_delete, name='posting_delete'),

    path('<int:posting_id>/comments/create/', views.create_comment, name="create_comment"),
    path('<int:posting_id>/comments/<int:comment_id>/delete/', views.delete_comment, name="delete_comment"),
    path('<int:posting_id>/comments/<int:comment_id>/update/', views.update_comment, name="update_comment"),
]

07_django/review/review/urls.py
from django.contrib import admin
from django.urls import path, include
urlpatterns = [
    path('admin/', admin.site.urls),
    # /board 로 시작하는 URL 은 전부 board/urls.py 로 보내라.
    path('board/', include('board.urls')),
    path('postings/', include('board_ad.urls')),
]

07_django/review/review_prj/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('board/', include('board.urls')),
    path('postings/', include('board_ad.urls')),
]

07_django/review/board/models.py
from django.db import models


# Create your models here.
class Article(models.Model):
    title = models.CharField(max_length=200)
    content = models.TextField(default='write contents')

    def __str__(self):
        return f'{self.id}: {self.title}'

07_django/review/board_ad/models.py
from django.db import models
from datetime import datetime


# Create your models here.
class Posting(models.Model):
    title = models.CharField(max_length=200, default='No Title')
    content = models.TextField(default='Write content Here')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f'{self.id}: {self.title[:20]}'


class Comment(models.Model):
    posting = models.ForeignKey(Posting, on_delete=models.CASCADE)
    content = models.CharField(max_length=200, default='No Comment')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f'{self.id}: {self.content[:30]}'

07_django/review/board/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Article

# Create your views here.

# id 불필요
def article_new(request):
    return render(request, 'board/new.html')

def article_create(request):
    article = Article()
    article.title = request.POST.get('input_title')
    article.content = request.POST.get('input_content')
    article.save()
    return redirect(f'/board_ad/articles/{article.id}/')


def article_list(request):
    articles = Article.objects.all()
    return render(request, 'board/list.html', {
        'articles': articles
    })

# id 필요
def article_detail(request, id):
    article = Article.objects.get(id=id)
    return render(request, 'board/detail.html', {
        'article': article
    })

def article_edit(request, id):
    article = Article.objects.get(id=id)
    return render(request, 'board/edit.html', {
        'article': article
    })

def article_update(request, id):
    article = Article.objects.get(id=id)
    article.title = request.POST.get('input_title')
    article.content = request.POST.get('input_content')
    article.save()
    return redirect(f'/board_ad/articles/{article.id}/')

def article_delete(request, id):
    article = Article.objects.get(id=id)
    article.delete()
    return redirect('/board_ad/articles/list/')













def index(request):
    return render(request, 'board/index.html')

def greeting(request, name, role):
    if role == 'admin':
        return render(request, 'board/greeting.html', {
            'name': name,
            'role': 'MASTER USER',
        })
    else:
        return render(request, 'board/greeting.html', { 'name': name, 'role': role })

07_django/review/board_ad/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponseNotAllowed #이건 포스트해야하는데 겟요청들어오면 안될때 쓰는거
from .models import Posting, Comment
from django.views.decorators.http import require_http_methods
from datetime import datetime

# Create your views here.
# Read
def posting_list(request):
    postings = Posting.objects.all()
    return render(request, 'board_ad/list.html', {
        'postings': postings
    })

def posting_detail(request, posting_id):
    posting = get_object_or_404(Posting, id=posting_id)
    # comments = Posting.comment_set.all()
    comments = Comment.objects.filter(posting=posting).order_by('-created_at')
    return render(request, 'board_ad/detail.html', {
        'posting': posting,
        'comments': comments,
    })

# Create
def posting_create(request):
    if request.method == 'POST':
        posting = Posting()
        posting.title = request.POST.get('title')
        posting.content = request.POST.get('content')
        posting.save()
        return redirect('board_ad:posting_detail', posting_id=posting.id)
    else:
        return render(request, 'board_ad/new.html')

# Update
@require_http_methods(['GET','POST'])
def posting_update(request, posting_id):
    posting = get_object_or_404(Posting, id=posting_id)
    if request.method == 'POST':
        posting.title = request.POST.get('posting_title')
        posting.content = request.POST.get('posting_content')
        posting.save()
        return redirect('board_ad:posting_detail', posting_id=posting.id)
    else:
        return render(request, 'board_ad/update.html', {
            'posting': posting
        })

# Delete
@require_http_methods(['POST'])
def posting_delete(request, posting_id):
    posting = get_object_or_404(Posting, id=posting_id)
    posting.delete()
    return redirect('board_ad:posting_list')


#Comment - create
@require_http_methods(['POST'])
def create_comment(request, posting_id):
    posting = get_object_or_404(Posting, id=posting_id)
    comment = Comment()
    comment.posting = posting
    comment.content = request.POST.get('comment')
    comment.save()
    return redirect('board_ad:posting_detail', posting_id)

@require_http_methods(['POST'])
def delete_comment(request, posting_id, comment_id):
    posting = get_object_or_404(Posting, id=posting_id)
    comment = get_object_or_404(Comment,id=comment_id)
    comment.delete()
    return redirect('board_ad:posting_detail', posting.id)

@require_http_methods(['GET', 'POST'])
def update_comment(request, posting_id, comment_id):
    posting = get_object_or_404(Posting, id=posting_id)
    comment = get_object_or_404(Comment,id=comment_id)
    if request.method == 'GET':
        return render(request, 'board_ad/comment_update.html', {'posting':posting, 'comment':comment})
    else:
        comment.content  =request.POST.get('comment')
        comment.save()
        return redirect('board_ad:posting_detail', posting.id)

07_django/review/board/templates/board/base.html
<!doctype html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
    {% block body %}

    {% endblock %}
</body>
</html>

07_django/review/board/templates/board/detail.html
{% extends 'board/base.html' %}

{% block body %}
    <h1>{{ article.title }}</h1>
    <p>{{ article.content }}</p>
    <hr>
    <a href="/board/articles/list/"><button>List</button></a>
    <a href="/board/articles/{{ article.id }}/edit/"><button>Edit</button></a>
    <form action="/board/articles/{{ article.id }}/delete/" method="POST">
        {% csrf_token %}
        <button type="submit">Delete</button>
    </form>
{% endblock %}

07_django/review/board/templates/board/edit.html
{% extends 'board/base.html' %}

{% block body %}
    <form action="/board/articles/{{ article.id }}/update/" method="POST">
        {% csrf_token %}
        <input name='input_title' type="text" value={{ article.title }}>
        <hr>
        <textarea name="input_content" id="" cols="30" rows="10">{{ article.content }}</textarea>
        <hr>
        <button type="submit">EDIT</button>
    </form>
{% endblock %}

07_django/review/board/templates/board/greeting.html
{% extends 'board/base.html' %}

{% block body %}
<h1>Hello, {{ name }}</h1>
<h2>You are {{ role }}</h2>
{% endblock %}

07_django/review/board/templates/board/index.html
{% extends 'board/base.html' %}

{% block body %}
<h1>hi</h1>
{% endblock %}

07_django/review/board/templates/board/list.html
{% extends 'board/base.html' %}

{% block body %}
    <h1>Article List</h1>
    <a href="/board/articles/new/"><button>New article</button></a>
    {% if articles %}
        <ol>
        {% for article in articles %}
            <li><a href="/board/articles/{{ article.id }}/">{{ article.title }}</a></li>
        {% endfor %}
        </ol>
    {% endif %}
{% endblock %}

07_django/review/board/templates/board/new.html
{% extends 'board/base.html' %}

{% block body %}
    <form action="/board/articles/create/" method="POST">
        {% csrf_token %}
        <input type="text" name="input_title">
        <hr>
        <textarea name="input_content" id="" cols="30" rows="10"></textarea>
        <hr>
        <button type="submit">CREATE</button>
    </form>
{% endblock %}

07_django/review/board_ad/templates/board_ad/base.html
<!doctype html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <title>Document</title>
</head>
<body>
<div class="container mt-5">
    {% block body %}

    {% endblock %}
</div>
</body>
</html>

07_django/review/board_ad/templates/board_ad/comment_update.html
{% extends 'board_ad/base.html' %}

{% block body %}
    <h1>{{ posting.title }}</h1>
    <p>{{ posting.content }}</p>
    <hr>
    <a href="{% url 'board_ad:posting_list' %}"><button>List</button></a>
    <a href="{% url 'board_ad:posting_update' posting.id %}"><button>Update</button></a>
    <form action="{% url 'board_ad:posting_delete' posting.id %}" method="POST">
        {% csrf_token %}
        <button type="submit" onclick="return confirm('진짜 지울구야?')">Delete</button>
    </form>
    <hr>

    <form method="POST" action="{%  url 'board_ad:update_comment' posting.id comment.id %}">
    {% csrf_token %}
        <label for="content">comment: </label>
        <input type="text" id="comment" name="comment" value="{{ comment.content }}">
        <input type="submit">
{% endblock %}

07_django/review/board_ad/templates/board_ad/create.html
{% extends 'board_ad/base.html' %}

{% block body %}
    <div>
    <h1>New Posting</h1>
    </div>
    <hr>
    <form action="{% url 'board_ad:posting_create' %}" method="POST">
        {% csrf_token %}
        <label for="posting_title">Title</label>
        <input type="text" name="posting_title" id="posting_title">
        <hr>
        <label for="posting_content">Content</label>
        <textarea name="posting_content" id="posting_content" cols="30" rows="10"></textarea>
        <hr>
        <button type="submit">CREATE</button>
    </form>
{% endblock %}

07_django/review/board_ad/templates/board_ad/detail.html
{% extends 'board_ad/base.html' %}

{% block body %}
    <h1>{{ posting.title }}</h1>
    <p>{{ posting.content }}</p>
    <hr>
    <a href="{% url 'board_ad:posting_list' %}"><button>List</button></a>
    <a href="{% url 'board_ad:posting_update' posting.id %}"><button>Update</button></a>
    <form action="{% url 'board_ad:posting_delete' posting.id %}" method="POST">
        {% csrf_token %}
        <button type="submit" onclick="return confirm('진짜 지울구야?')">Delete</button>
    </form>
    <hr>

    <form method="POST" action="{%  url 'board_ad:create_comment' posting.id %}">
    {% csrf_token %}
        <label for="content">comment: </label>
        <input type="text" id="comment" name="comment">
        <input type="submit">
    </form>

    <hr>
    <section>
    <ul>
    {% for comment in comments %}
        <li>{{ comment.content }}</li>
        <span>{{  comment.created_at }}</span>
        {% if comment.created_at != comment.updated_at %}
            <span class="text-muted">{{ comment.updated_at }}</span>
        {% endif %}
        <form action="{% url 'board_ad:delete_comment' posting.id comment.id %}" method="POST">
            {% csrf_token %}
                <input type="submit" value="delete">
        </form>
        <button><a href="{% url 'board_ad:update_comment' posting.id comment.id %}"> update </a></button>
    {% endfor %}
    </ul>
    </section>
{% endblock %}

07_django/review/board_ad/templates/board_ad/edit.html
<form action="/board/articles/{{ article.id }}/update/" method="post">
    {% csrf_token %}
    <input name="input_title" type="text" value="{{ article.title }}">
    <textarea name="input_content" cols="30" rows="10">{{ article.content }}</textarea>
    <button type="submit">UPDATE!</button>
</form>

07_django/review/board_ad/templates/board_ad/greeting.html
{% extends 'board/base.html' %}

{% block body %}
    <h1>Hello {{ name }}</h1>
    <h2>You are {{ role }}</h2>
{% endblock %}

07_django/review/board_ad/templates/board_ad/index.html
{% extends 'board/base.html' %}

{% block body %}
    <h1>This is INDEX page</h1>
{% endblock %}

07_django/review/board_ad/templates/board_ad/list.html
{% extends 'board_ad/base.html' %}

{% block body %}
    <h1>Posting List</h1>
    <a href="{% url 'board_ad:posting_create' %}"><button>New posting</button></a>
    {% if postings %}
        <ol>
        {% for posting in postings %}
            <li><a href="{% url 'board_ad:posting_detail' posting.id %}">{{ posting.title }}</a></li>
        {% endfor %}
        </ol>
    {% endif %}
{% endblock %}

07_django/review/board_ad/templates/board_ad/new.html
{% extends 'board_ad/base.html' %}
{% block body %}
    <form action="{% url 'board_ad:posting_create' %}" method="post">
        {% csrf_token %}
        <div>
            <label for="input_title">Title: </label>
            <input id="input_title" name="title" type="text">
        </div>
        <div>
            <label for="input_content">Content: </label>
            <textarea id="input_content" name="content" cols="30" rows="10"></textarea>
        </div>
        <div>
            <button type="submit">CREATE!</button>
        </div>
    </form>
{% endblock %}

07_django/review/board_ad/templates/board_ad/update.html
{% extends 'board_ad/base.html' %}

{% block body %}
    <form action="{% url 'board_ad:posting_update' posting.id %}" method="POST">
        {% csrf_token %}
        <div>
            <label for="posting_title">Title</label>
            <input name='posting_title' type="text" value={{ posting.title }} id="posting_title">
        </div>
        <hr>
        <div>
            <label for="posting_content">Content</label>
            <textarea name="posting_content" id="posting_content" cols="30" rows="10">{{ posting.content }}</textarea>
        </div>
        <hr>
        <div>
            <button type="submit">Update post</button>
        </div>
    </form>
{% endblock %}